version: '3.2'
services:
  web:
    image: php:7-apache

    volumes:
      - ./src/:/var/www/html/
    ports:
      - 8081:80
    networks:
      - back
  db:
    image: mysql:5
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
    networks:
      - back
  myadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - 8083:80
    environment:
      - PMA_HOST=db
      - PMA_USER=homestead
      - PMA_PASSWORD=secret
    networks:
      - back
networks:
  back:
